root = "."
tmp_dir = "tmp"

[build]
  # automatically build this file
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  # if build successful, run this binary
  bin = "./tmp/main"
  # watch these extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
  # ignore these folders
  exclude_dir = ["assets", "tmp", "vendor"]
  # Watch for new files
  include_file = []
  # Delay in ms after file change
  delay = 1000
  # Stop running old binary when build errors occur
  stop_on_error = true
  # Send interrupt signal before killing process (windows support)
  send_interrupt = false
  # Delay in ms after interrupt signal
  kill_delay = 500

[log]
  time = true
